services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: maze_user
      POSTGRES_PASSWORD: maze_pass
      POSTGRES_DB: maze_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maze_user -d maze_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: maze_backend
    command: >
      sh -c "python seed.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://maze_user:maze_pass@db:5432/maze_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: